//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceWCF
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceWCF.IReportService")]
    public interface IReportService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportService/GetData", ReplyAction="http://tempuri.org/IReportService/GetDataResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceWCF.GetDataResponse> GetDataAsync(ServiceWCF.GetDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportService/Version", ReplyAction="http://tempuri.org/IReportService/VersionResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceWCF.VersionResponse> VersionAsync(ServiceWCF.VersionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportService/GetRigobject", ReplyAction="http://tempuri.org/IReportService/GetRigobjectResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceWCF.GetRigobjectResponse> GetRigobjectAsync(ServiceWCF.GetRigobjectRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportService/GetDs", ReplyAction="http://tempuri.org/IReportService/GetDsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceWCF.GetDsResponse> GetDsAsync(ServiceWCF.GetDsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportService/EventLogForRig", ReplyAction="http://tempuri.org/IReportService/EventLogForRigResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceWCF.EventLogForRigResponse> EventLogForRigAsync(ServiceWCF.EventLogForRigRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportService/GetTestBeds", ReplyAction="http://tempuri.org/IReportService/GetTestBedsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceWCF.GetTestBedsResponse> GetTestBedsAsync(ServiceWCF.GetTestBedsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportService/GetEventTypes", ReplyAction="http://tempuri.org/IReportService/GetEventTypesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceWCF.GetEventTypesResponse> GetEventTypesAsync(ServiceWCF.GetEventTypesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportService/GetDummy", ReplyAction="http://tempuri.org/IReportService/GetDummyResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceWCF.GetDummyResponse> GetDummyAsync(ServiceWCF.GetDummyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportService/GetPerson", ReplyAction="http://tempuri.org/IReportService/GetPersonResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceWCF.GetPersonResponse> GetPersonAsync(ServiceWCF.GetPersonRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetData", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDataRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int value;
        
        public GetDataRequest()
        {
        }
        
        public GetDataRequest(int value)
        {
            this.value = value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDataResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDataResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GetDataResult;
        
        public GetDataResponse()
        {
        }
        
        public GetDataResponse(string GetDataResult)
        {
            this.GetDataResult = GetDataResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WCFReportLib")]
    public partial class ReplyMessage
    {
        
        private string replyField;
        
        private int idField;
        
        private bool idFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string Reply
        {
            get
            {
                return this.replyField;
            }
            set
            {
                this.replyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified
        {
            get
            {
                return this.idFieldSpecified;
            }
            set
            {
                this.idFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WCFReportLib")]
    public partial class Person
    {
        
        private int ageField;
        
        private bool ageFieldSpecified;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Age
        {
            get
            {
                return this.ageField;
            }
            set
            {
                this.ageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AgeSpecified
        {
            get
            {
                return this.ageFieldSpecified;
            }
            set
            {
                this.ageFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="Bridge.TestBed", Namespace="http://schemas.datacontract.org/2004/07/ReportDao.Model")]
    public partial class BridgeTestBed
    {
        
        private int testBedIdField;
        
        private bool testBedIdFieldSpecified;
        
        private string testBedNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int TestBedId
        {
            get
            {
                return this.testBedIdField;
            }
            set
            {
                this.testBedIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TestBedIdSpecified
        {
            get
            {
                return this.testBedIdFieldSpecified;
            }
            set
            {
                this.testBedIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string TestBedName
        {
            get
            {
                return this.testBedNameField;
            }
            set
            {
                this.testBedNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="Bridge.FilterParameters", Namespace="http://schemas.datacontract.org/2004/07/ReportDao.Model")]
    public partial class BridgeFilterParameters
    {
        
        private System.DateTime startDateField;
        
        private bool startDateFieldSpecified;
        
        private System.DateTime stopDateField;
        
        private bool stopDateFieldSpecified;
        
        private BridgeFilterParametersGroupByOperator withGroupingField;
        
        private bool withGroupingFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime StartDate
        {
            get
            {
                return this.startDateField;
            }
            set
            {
                this.startDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StartDateSpecified
        {
            get
            {
                return this.startDateFieldSpecified;
            }
            set
            {
                this.startDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime StopDate
        {
            get
            {
                return this.stopDateField;
            }
            set
            {
                this.stopDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StopDateSpecified
        {
            get
            {
                return this.stopDateFieldSpecified;
            }
            set
            {
                this.stopDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public BridgeFilterParametersGroupByOperator WithGrouping
        {
            get
            {
                return this.withGroupingField;
            }
            set
            {
                this.withGroupingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool WithGroupingSpecified
        {
            get
            {
                return this.withGroupingFieldSpecified;
            }
            set
            {
                this.withGroupingFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="Bridge.FilterParameters.GroupByOperator", Namespace="http://schemas.datacontract.org/2004/07/ReportDao.Model")]
    public enum BridgeFilterParametersGroupByOperator
    {
        
        /// <remarks/>
        Year,
        
        /// <remarks/>
        Month,
        
        /// <remarks/>
        Week,
        
        /// <remarks/>
        Day,
        
        /// <remarks/>
        Date,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="Bridge.EventType", Namespace="http://schemas.datacontract.org/2004/07/ReportDao.Model")]
    public partial class BridgeEventType
    {
        
        private string eventTypeDescriptionField;
        
        private int eventTypeIdField;
        
        private bool eventTypeIdFieldSpecified;
        
        private System.Nullable<int> eventTypeSubIdField;
        
        private bool eventTypeSubIdFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string EventTypeDescription
        {
            get
            {
                return this.eventTypeDescriptionField;
            }
            set
            {
                this.eventTypeDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int EventTypeId
        {
            get
            {
                return this.eventTypeIdField;
            }
            set
            {
                this.eventTypeIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EventTypeIdSpecified
        {
            get
            {
                return this.eventTypeIdFieldSpecified;
            }
            set
            {
                this.eventTypeIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<int> EventTypeSubId
        {
            get
            {
                return this.eventTypeSubIdField;
            }
            set
            {
                this.eventTypeSubIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EventTypeSubIdSpecified
        {
            get
            {
                return this.eventTypeSubIdFieldSpecified;
            }
            set
            {
                this.eventTypeSubIdFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WCFReportLib.Mock")]
    public partial class RigRecord
    {
        
        private int categoryIdField;
        
        private bool categoryIdFieldSpecified;
        
        private string eventNameField;
        
        private System.DateTime eventTimeField;
        
        private bool eventTimeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int CategoryId
        {
            get
            {
                return this.categoryIdField;
            }
            set
            {
                this.categoryIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CategoryIdSpecified
        {
            get
            {
                return this.categoryIdFieldSpecified;
            }
            set
            {
                this.categoryIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string EventName
        {
            get
            {
                return this.eventNameField;
            }
            set
            {
                this.eventNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime EventTime
        {
            get
            {
                return this.eventTimeField;
            }
            set
            {
                this.eventTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EventTimeSpecified
        {
            get
            {
                return this.eventTimeFieldSpecified;
            }
            set
            {
                this.eventTimeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WCFReportLib.Mock")]
    public partial class RigObject
    {
        
        private RigRecord[] rigDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=0)]
        public RigRecord[] RigData
        {
            get
            {
                return this.rigDataField;
            }
            set
            {
                this.rigDataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Version", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class VersionRequest
    {
        
        public VersionRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="VersionResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class VersionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ServiceWCF.ReplyMessage VersionResult;
        
        public VersionResponse()
        {
        }
        
        public VersionResponse(ServiceWCF.ReplyMessage VersionResult)
        {
            this.VersionResult = VersionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRigobject", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetRigobjectRequest
    {
        
        public GetRigobjectRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRigobjectResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetRigobjectResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ServiceWCF.RigObject GetRigobjectResult;
        
        public GetRigobjectResponse()
        {
        }
        
        public GetRigobjectResponse(ServiceWCF.RigObject GetRigobjectResult)
        {
            this.GetRigobjectResult = GetRigobjectResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDs", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDsRequest
    {
        
        public GetDsRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ServiceWCF.ArrayOfXElement GetDsResult;
        
        public GetDsResponse()
        {
        }
        
        public GetDsResponse(ServiceWCF.ArrayOfXElement GetDsResult)
        {
            this.GetDsResult = GetDsResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
    public partial class ArrayOfKeyValueOfdateTimeintKeyValueOfdateTimeint
    {
        
        private System.DateTime keyField;
        
        private int valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime Key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EventLogForRig", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class EventLogForRigRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ServiceWCF.BridgeEventType eventType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ServiceWCF.BridgeFilterParameters filterParameters;
        
        public EventLogForRigRequest()
        {
        }
        
        public EventLogForRigRequest(ServiceWCF.BridgeEventType eventType, ServiceWCF.BridgeFilterParameters filterParameters)
        {
            this.eventType = eventType;
            this.filterParameters = filterParameters;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EventLogForRigResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class EventLogForRigResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("KeyValueOfdateTimeint", Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays", IsNullable=false)]
        public ServiceWCF.ArrayOfKeyValueOfdateTimeintKeyValueOfdateTimeint[] EventLogForRigResult;
        
        public EventLogForRigResponse()
        {
        }
        
        public EventLogForRigResponse(ServiceWCF.ArrayOfKeyValueOfdateTimeintKeyValueOfdateTimeint[] EventLogForRigResult)
        {
            this.EventLogForRigResult = EventLogForRigResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTestBeds", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetTestBedsRequest
    {
        
        public GetTestBedsRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTestBedsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetTestBedsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/ReportDao.Model")]
        public ServiceWCF.BridgeTestBed[] GetTestBedsResult;
        
        public GetTestBedsResponse()
        {
        }
        
        public GetTestBedsResponse(ServiceWCF.BridgeTestBed[] GetTestBedsResult)
        {
            this.GetTestBedsResult = GetTestBedsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetEventTypes", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetEventTypesRequest
    {
        
        public GetEventTypesRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetEventTypesResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetEventTypesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/ReportDao.Model")]
        public ServiceWCF.BridgeEventType[] GetEventTypesResult;
        
        public GetEventTypesResponse()
        {
        }
        
        public GetEventTypesResponse(ServiceWCF.BridgeEventType[] GetEventTypesResult)
        {
            this.GetEventTypesResult = GetEventTypesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDummy", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDummyRequest
    {
        
        public GetDummyRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDummyResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDummyResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GetDummyResult;
        
        public GetDummyResponse()
        {
        }
        
        public GetDummyResponse(string GetDummyResult)
        {
            this.GetDummyResult = GetDummyResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPerson", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetPersonRequest
    {
        
        public GetPersonRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPersonResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetPersonResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/WCFReportLib")]
        public ServiceWCF.Person[] GetPersonResult;
        
        public GetPersonResponse()
        {
        }
        
        public GetPersonResponse(ServiceWCF.Person[] GetPersonResult)
        {
            this.GetPersonResult = GetPersonResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public interface IReportServiceChannel : ServiceWCF.IReportService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public partial class ReportServiceClient : System.ServiceModel.ClientBase<ServiceWCF.IReportService>, ServiceWCF.IReportService
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ReportServiceClient() : 
                base(ReportServiceClient.GetDefaultBinding(), ReportServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.NetTcpEndpoint.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ReportServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(ReportServiceClient.GetBindingForEndpoint(endpointConfiguration), ReportServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ReportServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ReportServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ReportServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ReportServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ReportServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceWCF.GetDataResponse> ServiceWCF.IReportService.GetDataAsync(ServiceWCF.GetDataRequest request)
        {
            return base.Channel.GetDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceWCF.GetDataResponse> GetDataAsync(int value)
        {
            ServiceWCF.GetDataRequest inValue = new ServiceWCF.GetDataRequest();
            inValue.value = value;
            return ((ServiceWCF.IReportService)(this)).GetDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceWCF.VersionResponse> ServiceWCF.IReportService.VersionAsync(ServiceWCF.VersionRequest request)
        {
            return base.Channel.VersionAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceWCF.VersionResponse> VersionAsync()
        {
            ServiceWCF.VersionRequest inValue = new ServiceWCF.VersionRequest();
            return ((ServiceWCF.IReportService)(this)).VersionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceWCF.GetRigobjectResponse> ServiceWCF.IReportService.GetRigobjectAsync(ServiceWCF.GetRigobjectRequest request)
        {
            return base.Channel.GetRigobjectAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceWCF.GetRigobjectResponse> GetRigobjectAsync()
        {
            ServiceWCF.GetRigobjectRequest inValue = new ServiceWCF.GetRigobjectRequest();
            return ((ServiceWCF.IReportService)(this)).GetRigobjectAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceWCF.GetDsResponse> ServiceWCF.IReportService.GetDsAsync(ServiceWCF.GetDsRequest request)
        {
            return base.Channel.GetDsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceWCF.GetDsResponse> GetDsAsync()
        {
            ServiceWCF.GetDsRequest inValue = new ServiceWCF.GetDsRequest();
            return ((ServiceWCF.IReportService)(this)).GetDsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceWCF.EventLogForRigResponse> ServiceWCF.IReportService.EventLogForRigAsync(ServiceWCF.EventLogForRigRequest request)
        {
            return base.Channel.EventLogForRigAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceWCF.EventLogForRigResponse> EventLogForRigAsync(ServiceWCF.BridgeEventType eventType, ServiceWCF.BridgeFilterParameters filterParameters)
        {
            ServiceWCF.EventLogForRigRequest inValue = new ServiceWCF.EventLogForRigRequest();
            inValue.eventType = eventType;
            inValue.filterParameters = filterParameters;
            return ((ServiceWCF.IReportService)(this)).EventLogForRigAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceWCF.GetTestBedsResponse> ServiceWCF.IReportService.GetTestBedsAsync(ServiceWCF.GetTestBedsRequest request)
        {
            return base.Channel.GetTestBedsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceWCF.GetTestBedsResponse> GetTestBedsAsync()
        {
            ServiceWCF.GetTestBedsRequest inValue = new ServiceWCF.GetTestBedsRequest();
            return ((ServiceWCF.IReportService)(this)).GetTestBedsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceWCF.GetEventTypesResponse> ServiceWCF.IReportService.GetEventTypesAsync(ServiceWCF.GetEventTypesRequest request)
        {
            return base.Channel.GetEventTypesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceWCF.GetEventTypesResponse> GetEventTypesAsync()
        {
            ServiceWCF.GetEventTypesRequest inValue = new ServiceWCF.GetEventTypesRequest();
            return ((ServiceWCF.IReportService)(this)).GetEventTypesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceWCF.GetDummyResponse> ServiceWCF.IReportService.GetDummyAsync(ServiceWCF.GetDummyRequest request)
        {
            return base.Channel.GetDummyAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceWCF.GetDummyResponse> GetDummyAsync()
        {
            ServiceWCF.GetDummyRequest inValue = new ServiceWCF.GetDummyRequest();
            return ((ServiceWCF.IReportService)(this)).GetDummyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceWCF.GetPersonResponse> ServiceWCF.IReportService.GetPersonAsync(ServiceWCF.GetPersonRequest request)
        {
            return base.Channel.GetPersonAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceWCF.GetPersonResponse> GetPersonAsync()
        {
            ServiceWCF.GetPersonRequest inValue = new ServiceWCF.GetPersonRequest();
            return ((ServiceWCF.IReportService)(this)).GetPersonAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.NetTcpEndpoint))
            {
                System.ServiceModel.NetTcpBinding result = new System.ServiceModel.NetTcpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.Security.Mode = System.ServiceModel.SecurityMode.None;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.NetTcpEndpoint))
            {
                return new System.ServiceModel.EndpointAddress("net.tcp://localhost:7778/");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ReportServiceClient.GetBindingForEndpoint(EndpointConfiguration.NetTcpEndpoint);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ReportServiceClient.GetEndpointAddress(EndpointConfiguration.NetTcpEndpoint);
        }
        
        public enum EndpointConfiguration
        {
            
            NetTcpEndpoint,
        }
    }
    
    [System.Xml.Serialization.XmlSchemaProviderAttribute(null, IsAny=true)]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public partial class ArrayOfXElement : object, System.Xml.Serialization.IXmlSerializable
    {
        
        private System.Collections.Generic.List<System.Xml.Linq.XElement> nodesList = new System.Collections.Generic.List<System.Xml.Linq.XElement>();
        
        public ArrayOfXElement()
        {
        }
        
        public virtual System.Collections.Generic.List<System.Xml.Linq.XElement> Nodes
        {
            get
            {
                return this.nodesList;
            }
        }
        
        public virtual System.Xml.Schema.XmlSchema GetSchema()
        {
            throw new System.NotImplementedException();
        }
        
        public virtual void WriteXml(System.Xml.XmlWriter writer)
        {
            System.Collections.Generic.IEnumerator<System.Xml.Linq.XElement> e = nodesList.GetEnumerator();
            for (
            ; e.MoveNext(); 
            )
            {
                ((System.Xml.Serialization.IXmlSerializable)(e.Current)).WriteXml(writer);
            }
        }
        
        public virtual void ReadXml(System.Xml.XmlReader reader)
        {
            for (
            ; (reader.NodeType != System.Xml.XmlNodeType.EndElement); 
            )
            {
                if ((reader.NodeType == System.Xml.XmlNodeType.Element))
                {
                    System.Xml.Linq.XElement elem = new System.Xml.Linq.XElement("default");
                    ((System.Xml.Serialization.IXmlSerializable)(elem)).ReadXml(reader);
                    Nodes.Add(elem);
                }
                else
                {
                    reader.Skip();
                }
            }
        }
    }
}
